config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :events
  resources :users, only: [:show, :edit, :update]
  resources :tweets, only: [:index, :new, :create]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :event

  validates :name,               presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :casts, dependent: :destroy
  has_many :event_images, dependent: :destroy
  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :casts, allow_destroy: true
  accepts_nested_attributes_for :event_images, allow_destroy: true
  accepts_nested_attributes_for :schedules, allow_destroy: true


  validates :title,                  presence: true
  validates :description,            presence: true
end

app/models/event_image.rb
class EventImage < ApplicationRecord
  belongs_to :event
  mount_uploader :img, ImageUploader
  # validates :img,               presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :event
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :tweet_images, dependent: :destroy
  has_many :comment
  belongs_to :user
  accepts_nested_attributes_for :tweet_images, allow_destroy: true
end

app/models/tweet_image.rb
class TweetImage < ApplicationRecord
  belongs_to :tweet
  mount_uploader :img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :tweets
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if user_signed_in?
      @events = current_user.events
      @schedules = []
      @events.each do |event|
        event.schedules.each do |sch|
          @schedules << sch
        end
      end
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.casts.build
    @event.event_images.build
    @event.schedules.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.save
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        redirect_to root_path
        # format.html { render :new }
        # format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :price, :place, :address, :remarks, :site_url,
      casts_attributes: [ :id, :name, :event_id, :_destroy ],
      event_images_attributes: [ :id, :img, :event_id, :_destroy ],
      schedules_attributes: [ :id, :start_time, :end_time, :event_id, :_destroy ]).merge(user_id: current_user.id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    if user_signed_in?
      @user = current_user
    end
    @tweets = Tweet.all.order("updated_at DESC").includes(:user)
  end

  def new
    @tweet = Tweet.new
    @tweet.tweet_images.build
    @user = current_user
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def tweet_params
    params.require(:tweet).permit(:text, tweet_images_attributes: [ :id, :img, :tweet_id, :_destroy ]).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order("updated_at DESC")
  end

  def edit

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_cast_fields.html.haml
.nested-fields
  .form-glid
    .new-event__field
      = f.text_field :name, class: 'event-form input-form'
      .remove-cast-btn
        = fa_icon 'times-circle'

app/views/events/_event_image_fields.html.haml
.nested-fields
  .ev-new-img-glid
    

app/views/events/_form.html.haml
= form_with model:@event,multipart: true do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .new-event
    = f.label :"タイトル"
    .new-event__field
      = f.text_field :title, class: "event-form title-form"
  .new-event
    = f.label :"詳細"
    .new-event__field
      = f.text_area :description, class: "event-form des-form"
  = f.fields_for :event_images do |i|
    .new-event
      = i.label :画像
      = render 'event_image_fields', f: i
    .add-links
      .add-img-btn
        = fa_icon 'plus-circle', class: 'add-btn--icon'
        追加
  .new-event
    = f.label :イベント期間
    .new-event__field
      = f.date_field :start_date, class: 'event-form st-date-form'
      〜
      = f.date_field :end_date, class: 'event-form en-date-form'
  = f.fields_for :schedules do |s|
    .new-event
      = s.label :開催日時
      = render 'schedule_fields', f: s
    .add-links
      = link_to_add_association f, :schedules, class: 'add-btn' do
        = fa_icon 'plus-circle', class: 'add-btn--icon'
        追加
  = f.fields_for :casts do |c|
    .new-event
      = c.label :出演者
      = render 'cast_fields', f: c
    .add-links
      .add-cast-btn
        = fa_icon 'plus-circle', class: 'add-btn--icon'
        追加
  .new-event
    = f.label :会場
    .new-event__field
      = f.text_field :place, class: 'event-form input-form'
  .new-event
    = f.label :会場住所
    .new-event__field
      = f.text_field :address, class: 'event-form input-form'
  .new-event
    = f.label :販売価格
    .new-event__field
      = f.number_field :price, class: 'event-form input-form'
  .new-event
    = f.label :予約url
    .new-event__field
      = f.url_field :site_url, class: 'event-form input-form'
  .new-event
    = f.label :備考
    .new-event__field
      = f.text_area :remarks, class: 'event-form remarks-form'
  .event-submit
    = f.submit '登録する', class: 'event-submit__btn'
  .event-return
    = link_to 'もどる', root_path, class: 'event-return__btn'

app/views/events/_schedule_fields.html.haml
.nested-fields
  .new-event__field
    = f.datetime_field :start_time, class: 'event-form st-time-form'
    〜
    = f.datetime_field :end_time, class: 'event-form en-time-form'
    = link_to_remove_association f, class: 'remove-btn' do
      = fa_icon 'times-circle'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
= render "layouts/side-bar"
.wrapper
  .side-bar
    
  .center-box

  .right-box
    .calendar-box
      #calendar

app/views/events/new.html.haml
.wrapper
  .left-box
    = render 'layouts/side-bar'
  .center-box
    .main-box
      .main-title
        イベント情報を入力
      .event-details
        = render 'form'


  .right-box
    #calendar

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Description:
  = @event.description
%p
  %b Start date:
  = @event.start_date
%p
  %b End date:
  = @event.end_date

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', root_path

app/views/layouts/_side-bar.html.haml
.side-bar
  = link_to  root_path, class: "side-bar_title" do
    = fa_icon 'connectdevelop'
    ShareCalendar
  .side-bar_nav
    = link_to root_path, class: "side-bar_link" do
      = fa_icon 'home', class: "side-bar_link--icon"
      ホーム
  .side-bar_nav
    = link_to "", class: "side-bar_link" do
      = fa_icon 'search', class: "side-bar_link--icon"
      検索
  -if user_signed_in?
    .side-bar_nav
      = link_to new_event_path, class: "side-bar_link" do
        = fa_icon 'clipboard', class: "side-bar_link--icon"
        予定を追加
    .side-bar_nav
      = link_to new_tweet_path, class: "side-bar_link" do
        = fa_icon 'pencil', class: "side-bar_link--icon"
        ツイート
    .side-bar_nav
      = link_to user_path(current_user), class: "side-bar_link" do
        - if current_user.image.present?
          = image_tag "#{current_user.image}", size: '20x20', class: 'side-bar_link--img'
          .side-bar_link__mypage
            マイページ
        -else
          = image_tag 'profile.webp', size: '25x25', class: 'side-bar_link--img'
          .side-bar_link__mypage
            マイページ
    .side-bar_nav
      = link_to events_path, class: "side-bar_link" do
        = fa_icon 'calendar', class: "side-bar_link--icon"
        マイカレンダー
    .side-bar_nav
      = link_to destroy_user_session_path, method: :delete, class: "side-bar_link" do
        = fa_icon 'user-times', class: "side-bar_link--icon"
        ログアウト
  - else
    .side-bar_nav
      = link_to new_user_registration_path, class: "side-bar_link" do
        = fa_icon 'search', class: "side-bar_link--icon"
        新規登録
    .side-bar_nav
      = link_to new_user_session_path, class: "side-bar_link" do
        = fa_icon 'search', class: "side-bar_link--icon"
        ログイン

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShareCalendar
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body{data: {turbolinks: "false"}}
    = yield

app/views/tweets/_tweet.haml
- @tweets.each do |tweet|
  .main-content-list
    .tweet-left
      - if tweet.user.image.present?
        = image_tag "#{tweet.user.image}", size: '40x40', class: 'list-icon'
      -else
        = image_tag 'profile.webp', size: '40x40', class: 'list-icon'
    .tweet-right
      .tweet-upper
        .tweet-upper__name
          = tweet.user.name
        .tweet-upper__right
          .tweet-upper__right__date
            = tweet.updated_at.strftime("%Y/%m/%d %H:%M")
          - if tweet.user == current_user
            .tweet-upper__right__btn
              .tweet-edit-link
                = fa_icon 'edit'
              .edit_hidden-ul
                = link_to "", class:"edit-hidden-li" do
                  編集
                = link_to "", class:"edit-hidden-li" do
                  削除
      .tweet-text
        = tweet.text
      - if tweet.tweet_images.present?
        .tweet-slider-wrap
          .tweet-images__slick
            - tweet.tweet_images.each do |image|
              = image_tag "#{image.img}"
          .tweet-images__thumbnail
            - tweet.tweet_images.each do |image|
              = image_tag "#{image.img}"
      .tweet-comment-btn
        = link_to "", class: "comment-btn-link" do
          = fa_icon 'comment-o'
          .tweet-comment-cr
          コメントする

app/views/tweets/_tweet_image_fields.html.haml
.nested-fields
  .tw-new-img-glid

app/views/tweets/index.html.haml
.wrapper
  .left-box
    = render 'layouts/side-bar'

  .center-box
    .main-content
      .select-tabs
        = link_to "ツイート", "", class: "tweet-tab active-tab"
        = link_to "イベント", "", class: "event-tab"
      .main-content-box
        = render 'tweet'

  .right-box
    #calendar

app/views/tweets/new.html.haml
.wrapper
  .left-box
    = render 'layouts/side-bar'

  .center-box
    .tweet_main-box
      .new-tweet-title
        投稿内容を入力
      = form_with model:@tweet, multipart: true do |f|
        - if @tweet.errors.any?
          #error_explanation
            %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
            %ul
              - @tweet.errors.full_messages.each do |message|
                %li= message
        .tweet_box
          = f.text_area :text ,class: "tweet_field", placeholder: "ここに内容を入力してください。"
          - if @user.image.present?
            = image_tag "#{@user.image}", size: '40x40', class: 'tweet_my-icon'
          -else
            = image_tag 'profile.webp', size: '40x40', class: 'tweet_my-icon'
          = f.fields_for :tweet_images do |i|
            = render 'tweet_image_fields', f: i
          -#     .tw-new-img-field
          -#       =i.label :"event-form-${r}",class: "img-field" do
          -#         .img-field__contents
          -#           = fa_icon "picture-o", class: "img-field--icon"
          -#           .img-field__contents--cr
          -#             画像を選択
          -#         = i.file_field :"event-form-${r}", class: "event-form__img"
          -#       .remove-img-btn
          -#         = fa_icon "times-circle-o"
            
          .tweet_image-btn
            = fa_icon 'plus-circle', class: 'tweet_add-icon'
            = fa_icon 'picture-o', class: 'tweet_image-icon'

          .tweet_submit
            = f.submit '投稿する', class: "tweet_submit--btn"
  
  .right-box
    #calendar

app/views/users/show.html.haml
.wrapper
  = render "layouts/side-bar"
  .center-box
    .head-content
      .my-header
      .my-header__details
        - if @user.image.present?
          = image_tag "#{@user.image}", size: '50x50', class: 'my-icon'
        -else
          = image_tag 'profile.webp', size: '50x50', class: 'my-icon'
        .my-name
          = @user.name
        .my-right-btn
          - if @user == current_user
            = link_to "編集", edit_user_registration_path, class:"my-right-btn__edit"
          - else
            - if current_user.following?(@user)
              = form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f|
                = f.hidden_field :follow_id, value: @user.id
                = f.submit 'フォロー中', class: 'my-right-btn__follow-now'
            - else
              = form_for(current_user.relationships.build) do |f|
                = f.hidden_field :follow_id, value: @user.id
                = f.submit 'フォロー', class: 'my-right-btn__follow'
        .my-introduction
          = @user.introduce
        .user-relationship
          .following
            .following__num
              = @user.followings.length
            .following__cr
              フォロー中
          .followed
            .followed__num
              = @user.followers.length
            .followed__cr
              フォロワー
    .my-main-content
      .select-tabs
        = link_to "ツイート", "", class: "tweet-tab active-tab"
        = link_to "イベント", "", class: "event-tab"
      .my-main-content-box
        = render 'tweets/tweet'
      


  .right-box
    #calendar